FORMAT: 1A

# Group TODO管理

## ToDo取得のエンドポイント [/Prod/todos]

### ToDo取得API [POST]

#### 処理概要

* 自ユーザーのToDoの取得を行う.

+ Request (application/json)

    + Headers

            Accept: application/json

    + Attributes
        + login_token: `1a772109-3694-42c9-9e2e-f141e789fd84` (string, required) - ログイントークン(format: uuid)

+ Response 200 (application/json)

    + Attributes
        + todos (array[object], fixed-type)
             + (object)
                 + login_token: `1a772109-3694-42c9-9e2e-f141e789fd84` (string, required) - ログイントークン(format: uuid)
                 + todo_id: `c0abebfd-0f27-44d4-8d39-7e8d67b937e6` (string, required) - ToDoID(format: uuid)
                 + todo_title: hogehoge (string, required) - ToDoのタイトル(format: string) - タイトルの上限は256文字
                 + todo_details: hugahuga (string, required) - ToDoの内容(format: string) - 内容の上限は512文字
                 + todo_expired_at_unix_time : 1655442000 (string) - ToDoの期限 unix時間(format: string)

+ Response 400 (application/json)

    + Attributes
        + todos: [] (array[], fixed-type)

+ Response 500 (application/json)

    + Attributes
        + todos: [] (array[], fixed-type)